backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "village"
    label: "गाँव की जानकारी"
    folder: "content/village"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "नाम", name: "title", widget: "string" }
      - { label: "विवरण", name: "body", widget: "markdown" }
